version: '3.3'
services:
  # mongo:
  #   image: mongo:focal
  #   container_name: mongo
  #   restart: always
  #   volumes:
  #     - ./data/db:/data/db
  #   ports:
  #     - 27017:27017

  # mongo-express:
  #   container_name: express
  #   image: mongo-express:1.0.0-alpha.4
  #   restart: always
  #   ports:
  #     - 8081:8081

  db:
      image: "mcr.microsoft.com/mssql/server"
      ports:
        - "1433:1433"
      volumes:
        - ./data/db:/var/opt/mssql/data
        - ./data/log:/var/opt/mssql/log

      environment:
          SA_PASSWORD: "sajadsajad1"
          ACCEPT_EULA: "Y"